modLoader="javafml"
loaderVersion="[${forge_min_version},)"
issueTrackerURL="${mod_issues}"
license="${license_name}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="${mod_credits}"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.${mod_id}]]
modId="catlib"
mandatory=true
versionRange="[${catlib_min_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory=false
ordering="AFTER"
side="BOTH"
