modLoader="javafml"
loaderVersion="${loader_version}"
issueTrackerURL="${mod_issues}"
license="GNUv3"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="${mod_credits}"
authors="${mod_authors}"
description="${mod_description}"
