modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/PersonTheCat/ore_stone_variants/issues"
license="GNUv3"

[[mods]] #mandatory
modId="osv"
version="${file.version}"
displayName="Ore Stone Variants"
logoFile="examplemod.png"
credits="MCP, pupnewfster"
authors="PersonTheCat"
description="to-do"
