modLoader="javafml"
loaderVersion="[${forge_min_version},)"
issueTrackerURL="${mod_issues}"
license="${license_name}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="${mod_credits}"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.catlib]]
modId="catlib"
mandatory=true
versionRange="[${catlib_version},)"
ordering="NONE"
side="BOTH"
